"""empty message

Revision ID: db92da3cff25
Revises: 
Create Date: 2020-03-24 11:42:16.010184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db92da3cff25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geojson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pro', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('Geo', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geojson_id'), 'geojson', ['id'], unique=False)
    op.create_table('mapping',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('admin_name1', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_mapping_key'), 'mapping', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_key'), table_name='mapping')
    op.drop_table('mapping')
    op.drop_index(op.f('ix_geojson_id'), table_name='geojson')
    op.drop_table('geojson')
    # ### end Alembic commands ###
